### ISSUE TITLE
TypeError: S.input is not a function

### ISSUE THREAD

**Issue by ebenoist** [gdborton/webpack-parallel-uglify-plugin#3]
Wanted to give this a try, but ran into some errors:

```JS
TypeError: S.input is not a function
    at next (eval at <anonymous> (/Users/ebenoist/dev/reverb/node_modules/webpack-parallel-uglify-plugin/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2078:25)
    at Object.parse (eval at <anonymous> (/Users/ebenoist/dev/reverb/node_modules/webpack-parallel-uglify-plugin/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2064:15)
    at addFile (/Users/ebenoist/dev/reverb/node_modules/webpack-parallel-uglify-plugin/node_modules/uglify-js/tools/node.js:70:33)
    at /Users/ebenoist/dev/reverb/node_modules/webpack-parallel-uglify-plugin/node_modules/uglify-js/tools/node.js:82:21
    at Array.forEach (native)
    at Object.exports.minify (/Users/ebenoist/dev/reverb/node_modules/webpack-parallel-uglify-plugin/node_modules/uglify-js/tools/node.js:77:26)
    at minify (/Users/ebenoist/dev/reverb/node_modules/webpack-parallel-uglify-plugin/lib/worker.js:5:17)
    at process.messageHandler (/Users/ebenoist/dev/reverb/node_modules/webpack-parallel-uglify-plugin/lib/worker.js:11:24)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
undefined:2078
            S.token = S.input();
                        ^
```

Let me know if I can help debug!

**Comment by gdborton** [comment]
@ebenoist Thanks for opening an issue!  Any steps that I can follow to reproduce?

Also, what version of node are you running this with? `node --version`

**Comment by gdborton** [comment]
@ebenoist ping.

**Comment by gdborton** [comment]
Ah, importing .svg files isn't a use case that I've ever had myself.  Are you importing this svg into your javascript file somewhere? I can dig into this, but if you could give me a stripped down example, that'd be really helpful.

**Comment by ebenoist** [comment]
@gdborton yup-- I'm importing svgs/pngs/jpgs directly into sass files which are being compiled by webpack as well. In a few places I also import images directly into JS/JSX files as well. They shouldn't be thrown through uglify so if the problem is just a missing exception/pattern match that might work?

I'll see if I can put together a demo tomorrow.

**Comment by gdborton** [comment]
@ebenoist I believe that this is fixed in v0.1.6.

**Comment by ebenoist** [comment]
Works for us! Thank you so much.

**Comment by ebenoist** [comment]
@gdborton Just wanted to say thank you again-- just reduced our bundling time from ~2m to ~50s
